### ISSUE TITLE
Enter should result in a newline instead of an 'unknown command'

### ISSUE THREAD

**Issue by davidem** [coolapso/hugo-theme-terminalcv#11]
Hi Carlos, 

awesome theme for Hugo! Thanks!

One tiny thing that annoyed me was that when you press 'enter', the prompt came back with an 'unknown command' error. Imho it should simply return a newline. Only when a real unknown command is typed, it should return the error. 

I've added 2 lines of code to catch '', which fixes it for me. Please check the pull request. Not sure if it is the best way to do this, but it works for me ;)

#10 

Cheers,

David

**Comment by coolapso** [comment]
https://github.com/coolapso/terminalcv/releases/tag/v1.1.2
