### ISSUE TITLE
"Erro" testando o tema 

### ISSUE THREAD

**Issue by 0xttfx** [coolapso/hugo-theme-terminalcv#16]
Olá Carlos

Tentei fazer um teste simples do seu tema... Porém estou tento o erro "Page Not Found"
Segue abaixo o procedimento executado e o erro obtido... 

Como não encontrei nenhum aviso quanto a teste subindo server local do hugo... Supus que deveria rodar! Ou não ?

```
hugo new site teste.hugo
cd teste.hugo/
git clone https://github.com/coolapso/hugo-theme-terminalcv.git themes/terminalcv
cp themes/terminalcv/exampleSite/config.yml .
hugo server -D --logLevel debug

Watching for changes in /home/0xttfx/Git/cv0xttfx.hugo/{archetypes,assets,content,data,i18n,layouts,static}
Watching for config changes in /home/0xttfx/Git/cv0xttfx.hugo/hugo.toml
Start building sites … 
hugo v0.121.2+extended linux/amd64 BuildDate=2024-02-07T00:00:00+00:00 VendorInfo=Fedora:0.121.2-1.fc40

INFO  copy static: syncing static files to /
INFO  build: running step process duration 52.943µs
INFO  build: running step assemble duration 53.384µs
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
INFO  build: running step render duration 694.339µs
INFO  build: running step postProcess duration 3.206µs

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 1 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
```

![erroCVCommand](https://github.com/coolapso/hugo-theme-terminalcv/assets/7905329/2cae2a8e-2dca-4529-b2d9-4fc503b51d42)

**Comment by coolapso** [comment]
Experimenta remover o hugo.toml. 

o `hugo new site` adiciona varios diretorios e ficheiros, un deletes é o hugo.toml que é utilizado por defeito ignorando o config.yaml. 

Tenho que melhorar o readme e talvez adicionar um exemplo com toml 

Edit: Na configuração theme esta comentado por defeito por questoes de teste .... remova o comentario ... deve estar assim: 

```
## Example Config file
baseURL: "https://example.com"
theme: "terminalcv"
title: "terminalcv"

```

**Comment by coolapso** [comment]
fixed: https://github.com/coolapso/hugo-theme-terminalcv/commit/d6fecbc18489cd807f05e6bc35e9fbafc95af6b2

**Comment by 0xttfx** [comment]
> fixed: [d6fecbc](https://github.com/coolapso/hugo-theme-terminalcv/commit/d6fecbc18489cd807f05e6bc35e9fbafc95af6b2)

Muito obrigado pela atenção Carlos! 
 "Funfou" belezinha! 🖖
