### ISSUE TITLE
Adding Certifications Suggestion

### ISSUE THREAD

**Issue by pauldavidjarvis** [coolapso/hugo-theme-terminalcv#4]
Hey, love your template and this idea! I was adding my own to my website and saw that you never included an option to discuss any certifications a person might hold so I added my own little bits to \themes\terminalcv\layouts\index.html and thought I'd add it a suggestion.

Added this to my toml file, had to use a converted to convert your yaml to toml:
```
[[params.certificate]]
certName = "Certificate Name"
company = "Certifying Company"
date = "Date of Completion"
description = "Lorem Ipsum"
```

Firstly included certificate as one of the available commands:
```
var availableCommands = ["all", "whois", 'social', 'work', 'education', 'certificate',
```

Next added a new function based on the education function and taking the company from the job function:
```
    /* Functions to be called by commands */
    function certificate () {
          term.echo("");
          {{ with .Site.Params.certificate }}
              {{ range . }}
			      term.echo("[[b;{{ .color | default "grey" }};]{{ .certName }}]");
                  term.echo("{{ .company }}");
                  term.echo("{{ .date }}");
                  {{ if .description }}
                      term.echo("{{ .description }}");
                  {{ end }}
                  term.echo("-------------------- ");
                  term.echo("");
              {{ end }}
          {{ end }}
      }
```

Then finally needed to include the case along with the rest in the Functions end section:
```
      /* Functions End */
	 case 'certificate':
                certificate();
                break;
```
And the case 'all' section:
```
            case 'all':
		   certificate();
```

**Comment by coolapso** [comment]
thanks a lot!! :D 

feel free to create a pull request ill be glad to review it and add it, otherwise I will see what i can do in the near future. :)

**Comment by coolapso** [comment]
Resolved with: https://github.com/4s3ti/terminalcv/pull/5
Release: https://github.com/4s3ti/terminalcv/releases/tag/v1.1.0

Thanks a lot @Jarvis4444 for your contribution! :muscle:
