### ISSUE TITLE
Make this multilanguage

### ISSUE THREAD

**Issue by gibranlp** [coolapso/hugo-theme-terminalcv#9]
Hi i love this theme, i was wondering if you can point  me in the right direction to make the theme multilanguage i would love to add spanish to it

**Comment by coolapso** [comment]
Hi, what exactly do you mean by multi language? 
you want to use The Hugo [multi langual](https://gohugo.io/content-management/multilingual/) mode? or you want to just have it in Spanish? 

I am not entirely sure what would be the best way to go about it ... but maybe create language sub directories and make the site builder use the templates for each language at build time.

**Comment by gibranlp** [comment]
Great ill start there, what im trying to do is to have both in english and spanish, see what i can do. thanks.

**Comment by coolapso** [comment]
Then yeah, start with the hugo Documentation and make the necessary adjustments,  :D
